require('plugins')
require('settings')
require('mappings')
require('colorschemes')

require('plugins')
require('plugins.lsp')
require('plugins.autopairs')
require('plugins.bufferline')
require('plugins.cmp')
require('plugins.comment')
require('plugins.gitsigns')
require('plugins.gitsigns')
require('plugins.nvim-tree')
require('plugins.prettier')
require('plugins.telescope')
require('plugins.treesitter')
